# Generated by Django 4.1.1 on 2022-09-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dir', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=15)),
                ('tel', models.CharField(max_length=15)),
            ],
        ),
    ]
